### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by BurtHarris** [fdeitelhoff/Simplex-Game-Web#1]
Hi.   Reviewing **package.json** I had a couple of questions/comments, but I'm just getting started...

  - I would expect `antlr4ts-cli` to be listed in `devDependencies`, it typically wouldn't be used at runtime. 

  - I'm surprised to see both `antlr4ts` and `antlr4` listed in the same project.   Our expectation is that `antlr4ts` will be a complete replacement for `antlr4`.   

I've got no experience w/ angular, but learning it has been on my todo list.   Nice looking set of dependencies, looking forward to this.  👍

**Comment by fdeitelhoff** [comment]
Hi. You're absolutely right. Both are already fixed in my local repository.

Maybe updating it soon.

**Comment by fdeitelhoff** [comment]
Both updated recently. Closing #2.
