### ISSUE TITLE
tsconfig files

### ISSUE THREAD

**Issue by BurtHarris** [fdeitelhoff/Simplex-Game-Web#2]
Where are you enabling the TypeScript options we discussed in tunnelvisionlabs/antlr4ts#326?

Reviewing **tsconfig.spec.json** and **tsconfig.app.json** in the root, they use `  "extends": "../tsconfig.json",` but that file isn't in the repository.

**Comment by fdeitelhoff** [comment]
It is in the root directory of the repository:

Simplex-Game-Web/tsconfig.json

**Comment by BurtHarris** [comment]
Oh, your right.   I opened VSCode in the wrong directory.
